version: '3.5'
services:
  app:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://ctfd:ctfd@db:5432/ctfd
  db:
    image: postgres:alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=ctfd
      - POSTGRES_PASSWORD=ctfd
  sut:
    image: alpine:3.11
    depends_on:
      - app
    command: /tmp/run_tests.sh
    volumes:
      - "./run_tests.sh:/tmp/run_tests.sh:ro"
