# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CTFd CI

on:
  push:
    paths:
    - '**.py'

jobs:
  build:

    runs-on: ubuntu-latest


    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mysql:
        image: mysql
        ports:
          - 3306:3306

      redis:
        image: redis
        ports:
          - 6379:6379

    strategy:
      matrix:
        python-version: ['2.7', '3.6']
        TESTING_DATABASE_URL: ['mysql+pymysql://root@localhost/ctfd', 'sqlite://', 'postgres://postgres@localhost/ctfd']

    name: Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install -r development.txt
            yarn install --non-interactive
            yarn global add prettier@1.17.0

      - name: Create postgres database
        run: psql -c 'create database ctfd;' -U postgres
      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Coverage
        run: codecov

